package fitpower.view;

/**
 *
 * @author Ismael
 */
public class JFrameAdmin extends javax.swing.JFrame {

    private JPanelCustomer jPanelCustomer;
    private JPanelGym jPanelGym;
    private JPanelRoutine jPanelRoutine;

    public JFrameAdmin() {
        initComponents();
        this.setVisible(true);
        this.setSize(1200, 650);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        JCustomer = new javax.swing.JMenu();
        CrudCustomer = new javax.swing.JMenuItem();
        JRotine = new javax.swing.JMenu();
        CrudRoutine = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Gym = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JCustomer.setText("Clientes");

        CrudCustomer.setText("Gestionar Clientes");
        CrudCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrudCustomerActionPerformed(evt);
            }
        });
        JCustomer.add(CrudCustomer);

        jMenuBar1.add(JCustomer);

        JRotine.setText("Rutinas");

        CrudRoutine.setText("Gestionar Rutinas");
        CrudRoutine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrudRoutineActionPerformed(evt);
            }
        });
        JRotine.add(CrudRoutine);

        jMenuBar1.add(JRotine);

        jMenu1.setText("Gym");

        Gym.setText("Gestionar Gym");
        jMenu1.add(Gym);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Nutricionista");

        jMenuItem1.setText("Gestionar Planes de Nutricion");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrudCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrudCustomerActionPerformed
        getContentPane().removeAll(); // Remover todos los componentes actuales
        this.jPanelCustomer = new JPanelCustomer();//crea un nuevo objeto
        this.jPanelCustomer.setSize(480, 480);//da tamaño al panel
        this.add(this.jPanelCustomer); //agrega con add al frame
        jPanelCustomer.repaint();//Repinta el panel para mejor funcionamiento

    }//GEN-LAST:event_CrudCustomerActionPerformed

    private void CrudRoutineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrudRoutineActionPerformed
        getContentPane().removeAll(); // Remover todos los componentes actuales
        this.jPanelRoutine = new JPanelRoutine();//crea un nuevo objeto
        this.jPanelRoutine.setSize(480, 480);//da tamaño al panel
        this.add(this.jPanelRoutine); //agrega con add al frame
        jPanelRoutine.repaint();//Repinta el panel para mejor funcionamiento
    }//GEN-LAST:event_CrudRoutineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CrudCustomer;
    private javax.swing.JMenuItem CrudRoutine;
    private javax.swing.JMenuItem Gym;
    private javax.swing.JMenu JCustomer;
    private javax.swing.JMenu JRotine;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
