package fitpower.view;

import java.awt.Color;

/**
 *
 * @author Ismael
 */
public class JPanelRoutine extends javax.swing.JPanel implements InterfacePanel {

      private final FieldValidator validador;
       private String crud;
    
    
    public JPanelRoutine() {
        initComponents();
        this.validador = new FieldValidator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_listar = new javax.swing.JButton();
        jtf_buscarPersona = new javax.swing.JTextField();
        jbtn_agregar = new javax.swing.JButton();

        jbtn_listar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_listar.setText("LISTAR POR DNI");
        jbtn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listarActionPerformed(evt);
            }
        });

        jtf_buscarPersona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_buscarPersona.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_buscarPersonaFocusGained(evt);
            }
        });
        jtf_buscarPersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_buscarPersonaKeyReleased(evt);
            }
        });

        jbtn_agregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_agregar.setText("AGREGAR");
        jbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jbtn_listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(27, 27, 27)
                    .addComponent(jtf_buscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(289, 289, 289)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtf_buscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(290, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listarActionPerformed
        //Actualizar el TableModel con la lista del controlador
       // this.tablaPersonaModelo.setPersonas(this.controlador.buscarTodasLasPersonas());

        //Refrescar el modelo en la tabla
      //   this.tablaPersonaModelo.fireTableDataChanged();

        limpiarTodosLosCampos();
        habilitarTodosLosCampos(false);
        habilitarTodosLosBotones(false);

        this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(true, this.jtf_buscarPersona);

       // this.personaSeleccionada = null;
    }//GEN-LAST:event_jbtn_listarActionPerformed

    private void jtf_buscarPersonaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_buscarPersonaFocusGained
        if (this.jtf_buscarPersona.isEditable()) {
       //     this.tablaPersonaModelo.setPersonas(this.controlador.buscarTodasLasPersonas());

            //Refrescar el modelo en la tabla
        //    this.tablaPersonaModelo.fireTableDataChanged();

            limpiarTodosLosCampos();
            habilitarTodosLosCampos(false);
            habilitarTodosLosBotones(false);

            this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarCampo(true, this.jtf_buscarPersona);

       /*     this.personaSeleccionada = null;

            this.jtb_persona.setEnabled(true);

            this.jlbl_alertaNombre.setIcon(null);
            this.jlbl_alertaApellido.setIcon(null);
            this.jlbl_alertaDNI.setIcon(null);

            this.jlbl_mensaje.setText("");*/
        }
    }//GEN-LAST:event_jtf_buscarPersonaFocusGained

    private void jtf_buscarPersonaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarPersonaKeyReleased
        if (this.jtf_buscarPersona.isEditable()) {
            //Actualizar el TableModel con la lista del controlador
          /*  this.tablaPersonaModelo.setPersonas(this.controlador.buscarPersonasPorDNI(this.jtf_buscarPersona.getText()));

            //Refrescar el modelo en la tabla
            this.tablaPersonaModelo.fireTableDataChanged();*/
        }
    }//GEN-LAST:event_jtf_buscarPersonaKeyReleased

    private void jbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarActionPerformed
        this.crud = "agregar";
       /* this.validador.limpiarCampo(this.jtf_nombre);
        this.validador.limpiarCampo(this.jtf_apellido);
        this.validador.limpiarCampo(this.jtf_dni);
        this.validador.limpiarCampo(this.jtf_buscarPersona);
        habilitarTodosLosBotones(false);
        habilitarTodosLosCampos(true);
        this.validador.habilitarBoton(false, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_aceptar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_cancelar, Color.red, Color.WHITE, null, null);
        this.validador.habilitarBoton(false, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(false, this.jtf_buscarPersona);

        this.jtb_persona.setEnabled(false);*/
    }//GEN-LAST:event_jbtn_agregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_agregar;
    private javax.swing.JButton jbtn_listar;
    private javax.swing.JTextField jtf_buscarPersona;
    // End of variables declaration//GEN-END:variables

    @Override
    public void habilitarTodosLosCampos(boolean estado) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void limpiarTodosLosCampos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void habilitarTodosLosBotones(boolean estado) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
