package fitpower.view;

import fitpower.controller.CustomerController;
import fitpower.model.Customer;
import fitpower.view.resource.TableCustomerModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Ismael
 */
public class JPanelCustomer extends javax.swing.JPanel implements InterfacePanel {

    private final FieldValidator validador;

    //variables de tabla
    private final TableCustomerModel tablaPersonaModelo;

    //variables de comboBox
    private DefaultComboBoxModel tipoPersonaModel;

    private final CustomerController controlador;
    private Customer personaSeleccionada;
    private final List<Customer> personas;
    private String crud;

    public JPanelCustomer() {
        //JTable vacio
        this.tablaPersonaModelo = new TableCustomerModel();
        this.validador = new FieldValidator();
        //JComboBox vacio
        this.tipoPersonaModel = new DefaultComboBoxModel();
        this.crud = "";

        this.personas = new ArrayList<>();
        this.controlador = new CustomerController();

        initComponents();
        this.setSize(1200, 800); // Ajusta el tamaño del JFrame para que sea más grande

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jtb_persona = new javax.swing.JTable();
        jbtn_listar = new javax.swing.JButton();
        jtf_buscarPersona = new javax.swing.JTextField();
        jbtn_agregar = new javax.swing.JButton();

        jScrollPaneTabla.setMaximumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setMinimumSize(new java.awt.Dimension(950, 750));
        jScrollPaneTabla.setPreferredSize(new java.awt.Dimension(950, 750));

        jtb_persona.setModel(tablaPersonaModelo);
        jScrollPaneTabla.setViewportView(jtb_persona);

        jbtn_listar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_listar.setText("LISTAR POR DNI");
        jbtn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listarActionPerformed(evt);
            }
        });

        jtf_buscarPersona.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtf_buscarPersona.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtf_buscarPersonaFocusGained(evt);
            }
        });
        jtf_buscarPersona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_buscarPersonaKeyReleased(evt);
            }
        });

        jbtn_agregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtn_agregar.setText("AGREGAR");
        jbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_buscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPaneTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_buscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 288, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listarActionPerformed
        //Actualizar el TableModel con la lista del controlador
        this.tablaPersonaModelo.setPersonas(this.controlador.buscarTodasLasPersonas());

        //Refrescar el modelo en la tabla
        this.tablaPersonaModelo.fireTableDataChanged();

        limpiarTodosLosCampos();
        habilitarTodosLosCampos(false);
        habilitarTodosLosBotones(false);

        this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(true, this.jtf_buscarPersona);

        this.personaSeleccionada = null;
    }//GEN-LAST:event_jbtn_listarActionPerformed

    private void jtf_buscarPersonaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtf_buscarPersonaFocusGained
        if (this.jtf_buscarPersona.isEditable()) {
            this.tablaPersonaModelo.setPersonas(this.controlador.buscarTodasLasPersonas());

            //Refrescar el modelo en la tabla
            this.tablaPersonaModelo.fireTableDataChanged();

            limpiarTodosLosCampos();
            habilitarTodosLosCampos(false);
            habilitarTodosLosBotones(false);

            this.validador.habilitarBoton(true, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarBoton(true, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
            this.validador.habilitarCampo(true, this.jtf_buscarPersona);

            this.personaSeleccionada = null;

            this.jtb_persona.setEnabled(true);

        }
    }//GEN-LAST:event_jtf_buscarPersonaFocusGained

    private void jtf_buscarPersonaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarPersonaKeyReleased
        if (this.jtf_buscarPersona.isEditable()) {
            //Actualizar el TableModel con la lista del controlador
            this.tablaPersonaModelo.setPersonas(this.controlador.buscarPersonasPorDNI(this.jtf_buscarPersona.getText()));

            //Refrescar el modelo en la tabla
            this.tablaPersonaModelo.fireTableDataChanged();
        }
    }//GEN-LAST:event_jtf_buscarPersonaKeyReleased

    private void jbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarActionPerformed
        this.crud = "agregar";
        this.validador.limpiarCampo(this.jtf_buscarPersona);
        habilitarTodosLosBotones(false);
        habilitarTodosLosCampos(true);
        this.validador.habilitarBoton(false, this.jbtn_listar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarBoton(false, this.jbtn_agregar, new Color(30, 132, 73), Color.WHITE, null, null);
        this.validador.habilitarCampo(false, this.jtf_buscarPersona);

        this.jtb_persona.setEnabled(false);
    }//GEN-LAST:event_jbtn_agregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JButton jbtn_agregar;
    private javax.swing.JButton jbtn_listar;
    private javax.swing.JTable jtb_persona;
    private javax.swing.JTextField jtf_buscarPersona;
    // End of variables declaration//GEN-END:variables

    @Override
    public void habilitarTodosLosCampos(boolean estado) {
        jtf_buscarPersona.setEnabled(estado);
        // Cuando tengas más campos, los agregás acá
    }

    @Override
    public void limpiarTodosLosCampos() {
        jtf_buscarPersona.setText("");
    }

    @Override
    public void habilitarTodosLosBotones(boolean estado) {
        jbtn_agregar.setEnabled(estado);
        jbtn_listar.setEnabled(estado);
        // Idem, si sumás más botones
    }
}
